export { default as Home } from './Home'
export { default as Coach } from './Coach'
export { default as Support } from './Support'
export { default as Mission } from './Mission'
export { default as Apply } from './Apply'
export { default as About } from './About'
export { default as PrivacyPage } from './PrivacyPage'
export { default as PrivacyDelete } from './PrivacyDelete'
